import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - CYBERVEST',
  description: 'Privacy Policy for CYBERVEST cyber risk quantification platform.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50 font-sans text-slate-900 selection:bg-emerald-100 selection:text-emerald-900 flex flex-col">
      <header className="w-full bg-white border-b border-slate-200 sticky top-0 z-10 shadow-sm">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#0F3F2E] flex items-center justify-center shadow-sm">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>
            </div>
            <span className="text-xl font-bold tracking-tight text-[#0F3F2E]">CYBERVEST</span>
          </div>
          <Link href="/login" className="text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors">
            Sign In
          </Link>
        </div>
      </header>

      <main className="flex-grow max-w-3xl mx-auto px-6 py-12 w-full">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 sm:p-12">
          <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
          <p className="text-slate-500 text-sm mb-10">Effective Date: [Insert Date Placeholder]</p>
          
          <div className="space-y-8 text-slate-700 text-base leading-relaxed">
            
            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">1. Introduction</h2>
              <p>
                Welcome to CYBERVEST. This Privacy Policy explains how [Company Legal Name Placeholder] ("we", "us", or "our") collects, uses, processes, and protects your information when you use the CYBERVEST application and related services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">2. Information We Collect</h2>
              <p className="mb-2">We collect the following types of information strictly to provide and improve our cyber risk quantification capabilities:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong>Account & Authentication Information:</strong> Email addresses and password data securely managed for user authentication.</li>
                <li><strong>Organization Information:</strong> Names, roles, and structural data of organization members for Role-Based Access Control (RBAC) and tenant isolation.</li>
                <li><strong>Cybersecurity Telemetry & Data:</strong> Asset inventory, vulnerabilities, framework compliance statuses, risk scenarios, and related financial or technical metrics input into or generated by CYBERVEST.</li>
                <li><strong>Evidence and Artifacts:</strong> Files, documents, and logs intentionally uploaded to the Evidence Vault to support compliance assessments and audits.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">3. How We Use Your Information</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>To authenticate users and enforce organizational boundaries.</li>
                <li>To perform FAIR-based (Factor Analysis of Information Risk) cyber risk analysis and generate financial exposure metrics.</li>
                <li>To provide optimization engines with necessary data for prioritizing security controls.</li>
                <li>To manage and securely store evidence documents tied to framework compliance.</li>
                <li>To generate executive and technical risk reports.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">4. Data Storage and Processing</h2>
              <p>
                Your data is stored and processed securely. We utilize third-party services such as Supabase for robust database management, isolated storage, and secure authentication. 
              </p>
              <p className="mt-2">
                All organizational data, including evidence files and risk telemetry, is strictly isolated using Row-Level Security (RLS) policies to ensure users can only access data belonging to their authorized organization.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">5. Security Measures</h2>
              <p>
                We implement industry-standard security measures, including but not limited to TLS encryption in transit, strict RBAC, and database-level RLS to protect your organization's sensitive risk data and telemetry against unauthorized access.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">6. Data Retention</h2>
              <p>
                We retain cybersecurity telemetry and evidence artifacts only for as long as necessary to fulfill the purposes outlined in this policy or as required by law. [Data Retention Period Placeholder]
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">7. Your Rights & Contact Information</h2>
              <p>
                Depending on your jurisdiction, you may have rights to access, correct, or delete your personal and organizational data. For inquiries, requests, or to contact our Data Protection Officer (if applicable), please reach out to us at:
              </p>
              <ul className="mt-3 space-y-1">
                <li><strong>Company:</strong> [Company Legal Name Placeholder]</li>
                <li><strong>Email:</strong> [Contact Email Placeholder]</li>
                <li><strong>Address:</strong> [Physical Address Placeholder]</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mb-3 border-b border-slate-100 pb-2">8. Policy Updates</h2>
              <p>
                We may update this Privacy Policy from time to time to reflect changes in our practices or applicable laws. Changes will be posted to this page with an updated effective date.
              </p>
            </section>

          </div>
        </div>
      </main>

      <footer className="w-full py-6 text-center text-xs text-slate-500 mt-auto bg-white border-t border-slate-200">
        <p>© 2025 CYBERVEST Intelligence Inc. All rights reserved.</p>
        <div className="flex items-center justify-center gap-4 mt-2">
          <Link href="/login" className="hover:text-slate-900 transition-colors">Sign In</Link>
          <span>•</span>
          <a href="#" className="hover:text-slate-900 transition-colors">Terms of Service</a>
        </div>
      </footer>
    </div>
  );
}
