import random
import uuid
from datetime import datetime, timedelta

def random_date(start, end):
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return start + timedelta(seconds=random_seconds)

def generate_organizations(count):
    orgs = []
    names = ["DemoFin Bank", "DemoNBFC", "DemoBroker", "DemoAMC", "DemoPaymentCo", 
             "DemoInsurance", "DemoSaaS", "DemoHealthcare", "DemoManufacturing", "DemoGovernment"]
    for i in range(count):
        name = names[i % len(names)]
        if i >= len(names):
            name += f" {i}"
        
        industry = "Financial Services" if "Fin" in name or "Bank" in name or "Broker" in name or "AMC" in name or "Payment" in name else (
            "Healthcare" if "Health" in name else (
            "Manufacturing" if "Manufacturing" in name else (
            "Technology" if "SaaS" in name else "Public Sector"
        )))
        
        orgs.append({
            "id": str(uuid.uuid4()),
            "name": name,
            "industry": industry,
            "country": "India",
            "organization_type": "Enterprise",
            "posture": random.choice(["strong", "moderate", "weak"])
        })
    return orgs

def generate_services(orgs, count_range):
    services = []
    service_templates = [
        ("Digital Payments", "critical", 500000000),
        ("Internet Banking", "high", 200000000),
        ("Core Banking", "critical", 1000000000),
        ("Trading Platform", "high", 150000000),
        ("Customer Identity", "critical", 0),
        ("HR", "medium", 0),
        ("Finance", "high", 50000000),
        ("CRM", "high", 100000000),
        ("Patient Management", "critical", 300000000),
        ("API Gateway", "critical", 0)
    ]
    
    for org in orgs:
        count = random.randint(count_range[0], count_range[1])
        for _ in range(count):
            template = random.choice(service_templates)
            services.append({
                "id": str(uuid.uuid4()),
                "organization_id": org["id"],
                "name": f"{template[0]} - {random.randint(1, 100)}",
                "description": f"Autogenerated {template[0]} service",
                "criticality": template[1],
                "annual_revenue_dependency": template[2]
            })
    return services

def generate_assets(orgs, services, count_range):
    assets = []
    asset_types = ["api", "web application", "database", "application server", "Linux server", 
                   "Windows server", "cloud workload", "container", "employee laptop", "network device"]
    
    for org in orgs:
        org_services = [s for s in services if s["organization_id"] == org["id"]]
        if not org_services: continue
        
        for s in org_services:
            count = random.randint(count_range[0], count_range[1])
            for _ in range(count):
                atype = random.choice(asset_types)
                internet_exposed = random.random() > 0.7 if org["posture"] == "strong" else random.random() > 0.4
                criticality = s["criticality"] if random.random() > 0.2 else random.choice(["high", "medium", "low"])
                
                assets.append({
                    "id": str(uuid.uuid4()),
                    "organization_id": org["id"],
                    "business_service_id": s["id"],
                    "name": f"{atype.title()} - {str(uuid.uuid4())[:8]}",
                    "asset_type": atype,
                    "environment": random.choice(["production", "staging", "development"]),
                    "criticality": criticality,
                    "internet_exposed": internet_exposed,
                    "data_sensitivity": "high" if criticality == "critical" else random.choice(["high", "medium", "low"]),
                    "owner": "IT Team",
                    "location": "AWS ap-south-1",
                    "description": "Autogenerated asset",
                    "source_type": "synthetic",
                    "data_quality_status": "verified",
                    "posture": org["posture"] # Internal tracking
                })
    return assets

def generate_vulnerabilities(assets, count_range):
    vulns = []
    for a in assets:
        count = random.randint(count_range[0], count_range[1])
        for _ in range(count):
            # Correlation: Internet exposed critical assets in weak orgs have more severe vulns
            base_score = random.uniform(4.0, 10.0)
            if a["internet_exposed"] and a["posture"] == "weak":
                base_score = random.uniform(7.0, 10.0)
                
            severity = "critical" if base_score >= 9.0 else ("high" if base_score >= 7.0 else "medium")
            known_exploited = random.random() > 0.8 if base_score < 7.0 else random.random() > 0.4
            epss = random.uniform(0.5, 0.99) if known_exploited else random.uniform(0.01, 0.3)
            
            vulns.append({
                "id": str(uuid.uuid4()),
                "cve_id": f"CVE-{random.randint(2010, 2024)}-{random.randint(1000, 99999)}",
                "asset_id": a["id"],
                "cvss_score": round(base_score, 1),
                "severity": severity,
                "attack_vector": "network" if a["internet_exposed"] else "adjacent",
                "attack_complexity": random.choice(["low", "high"]),
                "privileges_required": random.choice(["none", "low", "high"]),
                "user_interaction": random.choice(["none", "required"]),
                "exploit_available": known_exploited or random.random() > 0.5,
                "known_exploited": known_exploited,
                "epss_score": round(epss, 3),
                "source": "synthetic",
                "is_synthetic": True
            })
    return vulns

def generate_events_incidents_controls(orgs, services, assets, vulns, profile_cfg):
    events = []
    incidents = []
    controls = []
    now = datetime.now()
    
    control_templates = ["MFA", "EDR", "Network Segmentation", "Vulnerability Patching", "Immutable Backup", "WAF", "SIEM"]
    
    for org in orgs:
        org_assets = [a for a in assets if a["organization_id"] == org["id"]]
        if not org_assets: continue
        
        # Controls
        ccount = random.randint(profile_cfg["controls_per_org"][0], profile_cfg["controls_per_org"][1])
        org_controls = []
        for _ in range(ccount):
            template = random.choice(control_templates)
            eff = random.uniform(0.7, 0.95) if org["posture"] == "strong" else random.uniform(0.3, 0.7)
            c = {
                "id": str(uuid.uuid4()),
                "organization_id": org["id"],
                "name": f"{template} - {random.randint(1,100)}",
                "control_type": "preventive",
                "implementation_cost": random.randint(10000, 200000),
                "implementation_time_days": random.randint(10, 90),
                "effectiveness": round(eff, 2),
                "implementation_status": "implemented" if random.random() > 0.2 else "planned",
                "source_type": "synthetic",
                "is_synthetic": True
            }
            controls.append(c)
            org_controls.append(c)
            
        # Events
        for a in org_assets:
            ecount = random.randint(profile_cfg["events_per_asset"][0], profile_cfg["events_per_asset"][1])
            for _ in range(ecount):
                events.append({
                    "id": str(uuid.uuid4()),
                    "asset_id": a["id"],
                    "event_type": random.choice(["authentication_failure", "suspicious_network_activity", "malware_detected"]),
                    "severity": random.choice(["low", "medium", "high"]),
                    "source": "synthetic",
                    "timestamp": random_date(now - timedelta(days=90), now),
                    "description": "Synthetic generated event",
                    "is_synthetic": True
                })
        
        # Incidents
        icount = random.randint(profile_cfg["incidents_per_org"][0], profile_cfg["incidents_per_org"][1])
        for _ in range(icount):
            a = random.choice(org_assets)
            org_vulns = [v for v in vulns if v["asset_id"] == a["id"]]
            vuln_id = random.choice(org_vulns)["id"] if org_vulns and random.random() > 0.5 else None
            
            # Correlation
            prob_factor = 1.0
            if a["internet_exposed"]: prob_factor *= 1.5
            if org["posture"] == "weak": prob_factor *= 2.0
            if vuln_id: prob_factor *= 1.5
            
            sev = "high" if prob_factor > 2.0 and random.random() > 0.3 else random.choice(["medium", "low"])
            if prob_factor > 3.0 and random.random() > 0.5: sev = "critical"
            
            date = random_date(now - timedelta(days=365), now)
            
            s = next((srv for srv in services if srv["id"] == a["business_service_id"]), None)
            
            # Financial Impact based on criticality
            base_loss = 10000
            if s and s["criticality"] == "critical": base_loss = 500000
            elif s and s["criticality"] == "high": base_loss = 100000
            
            direct = base_loss * random.uniform(0.5, 1.5)
            indirect = direct * random.uniform(0.1, 0.5)
            
            incidents.append({
                "id": str(uuid.uuid4()),
                "organization_id": org["id"],
                "asset_id": a["id"],
                "business_service_id": a["business_service_id"],
                "incident_type": "data_breach" if sev in ["high", "critical"] else "service_disruption",
                "severity": sev,
                "incident_date": date,
                "detected_at": date + timedelta(hours=random.randint(1, 48)),
                "resolved_at": date + timedelta(days=random.randint(1, 14)),
                "vulnerability_id": vuln_id,
                "attack_vector": "network" if a["internet_exposed"] else "internal",
                "data_compromised": sev in ["high", "critical"],
                "records_affected": random.randint(1000, 1000000) if sev in ["high", "critical"] else 0,
                "downtime_hours": random.randint(1, 72),
                "direct_loss": round(direct, 2),
                "indirect_loss": round(indirect, 2),
                "total_loss": round(direct + indirect, 2),
                "source_type": "synthetic",
                "is_synthetic": True,
                "description": "Synthetic generated incident"
            })
            
    return events, incidents, controls
